# %% [markdown]
# # Recovery Capacity Analysis - Multiple Correlations
#
# ## Overview
#
# This script analyzes the **autonomous recovery (AR) capacity** of Continuous Hopfield
# Networks (CHN) after sleep-based consolidation. It determines the maximum number of
# patterns (K) a network of size N can reliably store and recover, as a function of
# pattern correlation (rho).
#
# ## What is Autonomous Recovery?
#
# During "sleep", networks are initialized from a neutral state (all units at 0.5) and
# allowed to evolve according to their trained dynamics with diagonal inhibition. The
# network spontaneously retrieves stored patterns one by one. A simulation is considered
# **successful** if all K patterns are retrieved before any spurious attractor is visited.
#
# ## Analysis Pipeline
#
# ### Part 1: Autonomous Recovery Analysis
#
# 1. **Load sleep simulation data** from CSV containing results across:
#    - Network sizes (N): ranging from small to large
#    - Number of patterns (K): varying load levels
#    - Pattern correlations (rho): 0.1, 0.25, 0.5, 0.75, 1.0
#
# 2. **Compute success rates** for each (N, K, rho) configuration:
#    - Success = all patterns found before spurious attractor
#    - Rate = fraction of repetitions that succeed
#
# 3. **Determine recovery capacity** at 90% threshold:
#    - For each (N, rho), find max K where success rate >= 90%
#    - This defines the "reliable" retrieval after storage capacity
#
# 4. **Generate visualizations**:
#    - 2x5 heatmap grid: success rates and retrieval speed per correlation
#    - Capacity curves: max K vs N for each correlation (B&W and colored)
#
# ### Part 2: Partial Cue Query Analysis
#
# For configurations that achieved >= 90% AR success, we test **partial cue retrieval**:
# networks are given incomplete patterns (only a fraction of units informed) and must
# recover the full pattern.
#
# **Key finding**: In the load regime allowing 90% successful AR, networks can recover
# patterns with as little as **10% informed units** (90% masked). Recovery succeeds as
# long as the partial cue has a smaller Hamming distance to the target pattern than to
# other stored patterns - demonstrating robust attractor basins.
#
# ## Data Sources
#
# - **Sleep results**: `Fig_load_SR_many_correlation_diag_inh_sleep/all_simulation_data.csv`
# - **Query results**: `partial_cue_correlations/all_simulation_data.csv`
#   (generated by `run_partial_cue_queries.py`)
#
# ## Output Figures
#
# 1. `recovery_capacity_correlations_heatmap.png` - 2x5 grid showing AR success rates
#    and retrieval iterations, with 90% threshold marked by stars
# 2. `recovery_capacity_correlations_line.png` - Capacity curves (B&W, publication style)
# 3. `recovery_capacity_correlations_line_colored.png` - Capacity curves (colored)
# 4. `partial_cue_recovery_5x4_heatmap.png` - Query success for different informed fractions

# %% Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).parent.parent))

# %%=========================================================================
# CONFIGURATION
# ==========================================================================

# Data source
DATA_PATH = Path("/home/saighi/Desktop/data/all_data_splited/sleep_simulations/Fig_load_SR_many_correlation_diag_inh_sleep/all_simulation_data.csv")

# Analysis parameters
CORRELATIONS_TO_PLOT = [0.1, 0.25, 0.5, 0.75, 1.0]  # noise_level values (displayed as rho)
SUCCESS_THRESHOLD = 0.9  # Fraction of simulations that must succeed (90%)

# Plot settings
SAVE_PLOTS = True
OUTPUT_DIR = Path(__file__).parent.parent / "plots"
DPI = 300

# %% Styling (matches SR_viz.py and push_retrieval_probability.py)
sns.set_style("darkgrid")
sns.set_context("paper", font_scale=1.5)
plt.rcParams['text.usetex'] = True
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Times']
plt.rcParams.update({
    'font.size': 20,
    'axes.labelsize': 20,
    'axes.titlesize': 20,
    'xtick.labelsize': 17,
    'ytick.labelsize': 17,
    'legend.fontsize': 18,
    'figure.titlesize': 20,
    'lines.linewidth': 2.5,
    'axes.linewidth': 1.5,
    'axes.grid': False,
    'font.weight': 'bold'
})

# Colormap for heatmaps (with grey for invalid data)
default_cmap_name = plt.rcParams["image.cmap"]
cmap_heatmap = mpl.cm.get_cmap(default_cmap_name).copy()
cmap_heatmap.set_bad(color="lightgrey")


# %% Helper functions
def get_spaced_indices(a, n, num_ticks=4):
    """Generate evenly spaced indices for tick marks."""
    return np.linspace(a, n, num_ticks, dtype=int)


def find_max_capacity(success_rates_df, network_size, threshold):
    """
    Find the maximum number of patterns where success rate >= threshold.
    """
    subset = success_rates_df[success_rates_df['network_size'] == network_size]
    successful = subset[subset['success_rate'] >= threshold]
    if len(successful) == 0:
        return 0
    return successful['num_patterns'].max()


# %% Load data
print("=" * 70)
print("LOADING DATA")
print("=" * 70)

data = pd.read_csv(DATA_PATH)
print(f"Loaded {len(data)} rows from:")
print(f"  {DATA_PATH}")

# %% Process data (following reference script logic)
df = data.copy()
df['num_patterns'] = df['num_patterns'].astype(int)

# Compute success metric: all patterns found before spurious
df["all_found"] = df["nb_fnd_pat"] == df["num_patterns"]

# First iteration where every pattern was found (per simulation)
first_all_found = (
    df.loc[df["all_found"]]
      .groupby("sim_ID")["query_iter"]
      .min()
      .rename("first_iter_all_fnd")
)
df = df.merge(first_all_found, on="sim_ID", how="left")
df["is_error_before_all_fnd"] = df["first_iter_all_fnd"].isna()
df["first_iter_all_fnd"] = df["first_iter_all_fnd"].fillna(0).astype(int) + 1

# Keep only the last iteration of each simulation
idx_last = df.groupby("sim_ID")["query_iter"].idxmax()
df_last = df.loc[idx_last].copy()

# Get unique values
all_net_sizes = np.sort(df_last['network_size'].unique())
all_num_patterns = np.sort(df_last['num_patterns'].unique())
all_correlations = np.sort(df_last['noise_level'].unique())

print(f"\nNetwork sizes: {len(all_net_sizes)} values ({all_net_sizes.min()} to {all_net_sizes.max()})")
print(f"Num patterns: {len(all_num_patterns)} values ({all_num_patterns.min()} to {all_num_patterns.max()})")
print(f"Correlations (noise_level): {list(all_correlations)}")

# Verify correlations to plot exist
correlations_to_plot = [c for c in CORRELATIONS_TO_PLOT if c in all_correlations]
print(f"Correlations to plot: {correlations_to_plot}")

# %% Compute success rates for each (correlation, network_size, num_patterns)
print("\n" + "=" * 70)
print("COMPUTING SUCCESS RATES")
print("=" * 70)

# For each configuration, compute success rate across repetitions
success_rates_all = df_last.groupby(
    ['noise_level', 'network_size', 'num_patterns']
).agg(
    success_rate=('is_error_before_all_fnd', lambda x: (~x).mean()),
    n_simulations=('sim_ID', 'count')
).reset_index()

print(f"Computed success rates for {len(success_rates_all)} configurations")

# %% Compute global color scale limits
global_max_error = 100  # percentage
global_max_iter = 0

for correlation in correlations_to_plot:
    sub = df_last.loc[df_last["noise_level"] == correlation].copy()
    sub["is_not_error_before_all_fnd"] = ~sub["is_error_before_all_fnd"]
    sub.loc[sub["is_error_before_all_fnd"], "first_iter_all_fnd"] = np.nan

    pt_itr = sub.pivot_table(
        values="first_iter_all_fnd",
        index="num_patterns",
        columns="network_size",
    )
    if not np.all(np.isnan(pt_itr.values)):
        global_max_iter = max(global_max_iter, np.nanmax(pt_itr.values))

print(f"\nColor scale ranges:")
print(f"  Success rate: 0 - {global_max_error}%")
print(f"  First iteration: 0 - {global_max_iter:.0f}")

# %% Figure 1: 2x5 Heatmap Grid (SR_viz style)
print("\n" + "=" * 70)
print("CREATING HEATMAP FIGURE")
print("=" * 70)

n_cols = len(correlations_to_plot)
x_tick_indices = get_spaced_indices(1, len(all_net_sizes) - 1, 4)
y_tick_indices = get_spaced_indices(1, len(all_num_patterns) - 1, 7)

r = 1.1
fig1, axes = plt.subplots(2, n_cols, figsize=(15/r, 8/r), sharey=True, sharex=True)

for i, correlation in enumerate(correlations_to_plot):
    sub = df_last.loc[df_last["noise_level"] == correlation].copy()
    sub["is_not_error_before_all_fnd"] = ~sub["is_error_before_all_fnd"]
    sub.loc[sub["is_error_before_all_fnd"], "first_iter_all_fnd"] = np.nan

    # Row 1: % simulations without errors (success rate)
    pt_err = sub.pivot_table(
        values="is_not_error_before_all_fnd",
        index="num_patterns",
        columns="network_size",
    )
    im1 = axes[0, i].imshow(pt_err * 100, vmin=0, vmax=global_max_error)
    axes[0, i].set_title(rf"$\rho={correlation}$")
    axes[0, i].invert_yaxis()
    axes[0, i].grid(False)

    # Add 90% threshold stars on Row 1
    success_rates_corr = success_rates_all[success_rates_all['noise_level'] == correlation]
    for net_size in all_net_sizes:
        max_cap = find_max_capacity(success_rates_corr, net_size, SUCCESS_THRESHOLD)
        if max_cap > 0:
            x_idx = list(pt_err.columns).index(net_size)
            y_idx = list(pt_err.index).index(max_cap)
            axes[0, i].plot(x_idx, y_idx, 'k*', markersize=8)

    # Row 2: First iteration (NaNs -> grey)
    pt_itr = (
        sub.pivot_table(
            values="first_iter_all_fnd",
            index="num_patterns",
            columns="network_size",
        )
        .reindex(index=all_num_patterns, columns=all_net_sizes)
    )
    masked_itr = np.ma.masked_invalid(pt_itr.values)
    im2 = axes[1, i].imshow(masked_itr, vmin=0, vmax=global_max_iter, cmap=cmap_heatmap)
    axes[1, i].invert_yaxis()
    axes[1, i].grid(False)

# Set ticks
for row in axes:
    for ax in row:
        ax.tick_params(axis='both', which='both', bottom=True, left=True,
                      top=False, right=False)
        ax.set_xticks(x_tick_indices, all_net_sizes[x_tick_indices])
        ax.set_yticks(y_tick_indices, all_num_patterns[y_tick_indices])

# Colorbars
cbar1_ax = fig1.add_axes([0.92, 0.56, 0.01, 0.3])
cbar1 = fig1.colorbar(im1, cax=cbar1_ax)
cbar1.set_ticks(np.linspace(0, 100, 5))
cbar1.set_ticklabels([f'{int(val)}' for val in np.linspace(0, 100, 5)])

cbar2_ax = fig1.add_axes([0.92, 0.14, 0.01, 0.3])
cbar2 = fig1.colorbar(im2, cax=cbar2_ax)
cbar2.set_ticks(np.linspace(0, global_max_iter, 5))
cbar2.set_ticklabels([f'{int(val)}' for val in np.linspace(1, global_max_iter, 5)])

# Axis labels
fig1.text(0.51, 0.04, 'Network size', ha='center', va='center')
fig1.text(0.07, 0.49, 'Nb stored pattern', ha='left', va='center', rotation=90)

if SAVE_PLOTS:
    OUTPUT_DIR.mkdir(exist_ok=True, parents=True)
    output_path = OUTPUT_DIR / f"recovery_capacity_correlations_heatmap.png"
    plt.savefig(output_path, dpi=DPI, bbox_inches='tight')
    print(f"\nSaved heatmap to: {output_path}")

plt.show()


# %% Figure 2: Combined Line Plot (all correlations)
print("\n" + "=" * 70)
print("CREATING LINE PLOT")
print("=" * 70)

# Line styles for different correlations
line_styles = ['-', '--', ':', '-.', (0, (3, 1, 1, 1))]  # solid, dashed, dotted, dashdot, densely dashdotted
markers = ['o', 's', '^', 'D', 'v']  # circle, square, triangle, diamond, inverted triangle

fig2, ax2 = plt.subplots(figsize=(10, 7))

capacity_data = {}

for idx, correlation in enumerate(correlations_to_plot):
    success_rates_corr = success_rates_all[success_rates_all['noise_level'] == correlation]

    capacities = []
    for net_size in all_net_sizes:
        max_cap = find_max_capacity(success_rates_corr, net_size, SUCCESS_THRESHOLD)
        capacities.append({
            'network_size': net_size,
            'max_capacity': max_cap,
        })

    cap_df = pd.DataFrame(capacities)
    capacity_data[correlation] = cap_df

    ax2.plot(cap_df['network_size'], cap_df['max_capacity'],
             linestyle=line_styles[idx], marker=markers[idx],
             color='black', linewidth=2.5, markersize=8,
             markerfacecolor='white', markeredgecolor='black', markeredgewidth=1.5,
             label=rf'$\rho={correlation}$')

ax2.set_xlabel(r'Network size ($N$)')
ax2.set_ylabel(r'Max retrievable patterns ($K$)')
ax2.set_title(rf'Recovery capacity at {int(SUCCESS_THRESHOLD*100)}\% threshold')

# Spine styling
for spine in ['bottom', 'left']:
    ax2.spines[spine].set_visible(True)
    ax2.spines[spine].set_color('black')
    ax2.spines[spine].set_linewidth(1.5)
for spine in ['top', 'right']:
    ax2.spines[spine].set_visible(False)

ax2.legend(loc='upper left', frameon=False)
plt.tight_layout()

if SAVE_PLOTS:
    output_path = OUTPUT_DIR / f"recovery_capacity_correlations_line.png"
    plt.savefig(output_path, dpi=DPI, bbox_inches='tight')
    print(f"Saved line plot to: {output_path}")

plt.show()


# %% Figure 2b: Combined Line Plot with COLORS (easier to read)
print("\n" + "=" * 70)
print("CREATING COLORED LINE PLOT")
print("=" * 70)

# Color palette (viridis-like for good contrast)
colors = ['#440154', '#3b528b', '#21918c', '#5ec962', '#fde725']  # viridis discrete

fig2b, ax2b = plt.subplots(figsize=(10, 7))

for idx, correlation in enumerate(correlations_to_plot):
    cap_df = capacity_data[correlation]

    ax2b.plot(cap_df['network_size'], cap_df['max_capacity'],
              linestyle='-', marker='o',
              color=colors[idx], linewidth=2.5, markersize=8,
              markerfacecolor=colors[idx], markeredgecolor='black', markeredgewidth=1,
              label=rf'$\rho={correlation}$')

ax2b.set_xlabel(r'Network size ($N$)')
ax2b.set_ylabel(r'Max retrievable patterns ($K$)')
ax2b.set_title(rf'Recovery capacity at {int(SUCCESS_THRESHOLD*100)}\% threshold')

# Spine styling
for spine in ['bottom', 'left']:
    ax2b.spines[spine].set_visible(True)
    ax2b.spines[spine].set_color('black')
    ax2b.spines[spine].set_linewidth(1.5)
for spine in ['top', 'right']:
    ax2b.spines[spine].set_visible(False)

ax2b.legend(loc='upper left', frameon=False)
plt.tight_layout()

if SAVE_PLOTS:
    output_path = OUTPUT_DIR / f"recovery_capacity_correlations_line_colored.png"
    plt.savefig(output_path, dpi=DPI, bbox_inches='tight')
    print(f"Saved colored line plot to: {output_path}")

plt.show()


# %% Display capacity table
print("\n" + "=" * 70)
print(f"RECOVERY CAPACITY ANALYSIS (threshold={SUCCESS_THRESHOLD:.0%})")
print("=" * 70)

for correlation in correlations_to_plot:
    cap_df = capacity_data[correlation]
    cap_df['capacity_ratio'] = cap_df['max_capacity'] / cap_df['network_size']
    avg_ratio = cap_df['capacity_ratio'].mean()
    print(f"\nCorrelation rho={correlation}: Average K/N = {avg_ratio:.4f}")

# Summary table
print("\n" + "-" * 60)
print(f"{'rho':>8} | {'Avg K/N':>10}")
print("-" * 60)
for correlation in correlations_to_plot:
    cap_df = capacity_data[correlation]
    cap_df['capacity_ratio'] = cap_df['max_capacity'] / cap_df['network_size']
    avg_ratio = cap_df['capacity_ratio'].mean()
    print(f"{correlation:>8} | {avg_ratio:>10.4f}")

print("=" * 70)


# %% [markdown]
# ## Partial Cue Query Analysis
#
# ### Motivation
#
# Beyond autonomous recovery (starting from neutral state), we want to understand how
# well trained networks perform **cued retrieval** - recovering a full pattern when
# given only partial information. This is analogous to pattern completion in biological
# memory systems.
#
# ### Methodology
#
# For each stored pattern in networks that achieved >= 90% AR success:
# 1. Construct a **partial cue** by keeping only `informed_fraction` of units at their
#    pattern values and setting the rest to neutral (0.5)
# 2. Initialize network with this partial cue
# 3. Let dynamics evolve (with noise, without inhibition)
# 4. Check if network converges to the correct pattern (winner-take-all comparison)
#
# ### Tested Informed Fractions
#
# We sweep over informed fractions from 20% down to as low as 2%:
# - 20% informed = 80% of units masked (set to neutral 0.5)
# - 10% informed = 90% masked
# - 5% informed = 95% masked
# - 2% informed = 98% masked
#
# ### Key Results
#
# In the load regime that allows 90% successful autonomous recovery, networks demonstrate
# remarkable pattern completion ability. With only **10% of units informed**, networks
# reliably recover the correct pattern. The critical factor is that the partial cue must
# correlate more strongly with the target pattern than with other stored patterns (i.e.,
# have a smaller Hamming distance). This confirms that the trained attractor basins are
# deep and well-separated.
#
# ### Visualization
#
# The 5x4 heatmap grid shows query success rates:
# - **Rows**: 5 correlation values (rho = 0.1 to 1.0)
# - **Columns**: 4 informed fractions (20%, 10%, 5%, 2%)
# - **Color**: Query success rate (0-100%)
# - **Grey cells**: Configurations below 90% AR threshold (not tested)

# %% Configuration for query analysis
TRAINED_NETWORKS_DIR = Path("/home/saighi/Desktop/AR_final/Autonomous_Recollection_CHN/simulations/main_write_sleep/data/trained_networks/Fig_load_SR_many_correlation_diag_inh")
QUERY_RESULTS_DIR = Path(__file__).parent.parent.parent / "data" / "query_results" / "partial_cue_correlations"
INFORMED_FRACTIONS = [0.2, 0.1, 0.05, 0.02]  # Fraction of units that keep pattern info

# %% Build mapping from (network_size, num_patterns, noise_level) -> trained network paths
print("\n" + "=" * 70)
print("BUILDING TRAINED NETWORK INDEX")
print("=" * 70)

from utils import read_parameters

trained_network_index = {}  # (network_size, num_patterns, noise_level) -> path

if TRAINED_NETWORKS_DIR.exists():
    for sim_dir in sorted(TRAINED_NETWORKS_DIR.iterdir()):
        if sim_dir.is_dir() and sim_dir.name.startswith("sim_nb_"):
            params_file = sim_dir / "parameters.data"
            if params_file.exists():
                params = read_parameters(params_file)
                key = (
                    int(params.get("network_size", 0)),
                    int(params.get("num_patterns", 0)),
                    params.get("noise_level", 0)
                )
                trained_network_index[key] = str(sim_dir)

print(f"Indexed {len(trained_network_index)} trained networks")

# %% Identify configurations with 90% success (eligible for query testing)
# Build eligibility directly from success_rates_all (no trained network check needed)
eligible_configs = set()

for corr in correlations_to_plot:
    subset = success_rates_all[
        (success_rates_all['noise_level'] == corr) &
        (success_rates_all['success_rate'] >= SUCCESS_THRESHOLD)
    ]
    for _, row in subset.iterrows():
        key = (int(row['network_size']), int(row['num_patterns']), corr)
        eligible_configs.add(key)

print(f"Found {len(eligible_configs)} configurations with >= {SUCCESS_THRESHOLD:.0%} success")

# %% Check if query results exist
query_csv_path = QUERY_RESULTS_DIR / "all_simulation_data.csv"

if query_csv_path.exists():
    print(f"\nLoading existing query results from: {query_csv_path}")
    query_df = pd.read_csv(query_csv_path)
    print(f"Loaded {len(query_df)} query results")
else:
    print(f"\nQuery results not found at: {query_csv_path}")
    print("Run scripts/recovery_capacity/run_partial_cue_queries.py first to generate query results.")
    query_df = None

# %% Build eligibility mask (configurations with >= 90% AR success)
# Create a 2D mask for each correlation: True = eligible (>= 90% success)
eligibility_masks = {}

print("\nBuilding eligibility masks...")
for corr in correlations_to_plot:
    mask = np.zeros((len(all_num_patterns), len(all_net_sizes)), dtype=bool)
    for i, np_val in enumerate(all_num_patterns):
        for j, ns_val in enumerate(all_net_sizes):
            key = (int(ns_val), int(np_val), corr)
            mask[i, j] = key in eligible_configs
    eligibility_masks[corr] = mask
    print(f"  rho={corr}: {mask.sum()} eligible cells (out of {mask.size})")

print(f"Eligibility masks built for {len(eligibility_masks)} correlations")

# %% Generate 5x4 heatmap grid if query results exist
if query_df is not None:
    print("\n" + "=" * 70)
    print("CREATING PARTIAL CUE HEATMAP (5x4 grid)")
    print("=" * 70)

    n_rows = len(correlations_to_plot)
    n_cols = len(INFORMED_FRACTIONS)

    # Prepare data structure for heatmaps
    # For each (correlation, informed_fraction), create pivot table
    query_pivots = {}

    for corr in correlations_to_plot:
        for inf in INFORMED_FRACTIONS:
            # Filter query results for this configuration
            # Note: CSV column is still 'informed_fraction' after C++ update
            subset = query_df[
                (query_df['noise_level'] == corr) &
                (np.isclose(query_df['informed_fraction'], inf, atol=0.001))
            ]

            if len(subset) > 0:
                # Compute success rate per (network_size, num_patterns)
                pivot = subset.groupby(['network_size', 'num_patterns']).agg(
                    success_rate=('recovered', 'mean')
                ).reset_index()
                pivot_table = pivot.pivot(
                    index='num_patterns',
                    columns='network_size',
                    values='success_rate'
                )
            else:
                pivot_table = pd.DataFrame()

            query_pivots[(corr, inf)] = pivot_table

    # Create figure
    fig_query, axes_query = plt.subplots(n_rows, n_cols, figsize=(16, 20), sharex=True, sharey=True)

    # Grey colormap for NaN (ineligible configs below 90% AR threshold)
    cmap_query = mpl.cm.get_cmap(default_cmap_name).copy()
    cmap_query.set_bad(color="lightgrey")

    for row_idx, corr in enumerate(correlations_to_plot):
        for col_idx, inf in enumerate(INFORMED_FRACTIONS):
            ax = axes_query[row_idx, col_idx]
            pivot = query_pivots[(corr, inf)]

            # Get eligibility mask for this correlation
            elig_mask = eligibility_masks[corr]

            if not pivot.empty:
                # Reindex to full grid, NaN for missing
                pivot_full = pivot.reindex(index=all_num_patterns, columns=all_net_sizes)
                data = pivot_full.values * 100

                # Apply eligibility mask: set ineligible configs to NaN (will show as grey)
                data_masked = np.where(elig_mask, data, np.nan)
                masked_data = np.ma.masked_invalid(data_masked)
                im = ax.imshow(masked_data, vmin=0, vmax=100, cmap=cmap_query, aspect='auto')
            else:
                # All grey (no data)
                empty_data = np.full((len(all_num_patterns), len(all_net_sizes)), np.nan)
                masked_data = np.ma.masked_invalid(empty_data)
                im = ax.imshow(masked_data, vmin=0, vmax=100, cmap=cmap_query, aspect='auto')

            ax.invert_yaxis()
            ax.grid(False)

            # Column titles (top row only)
            if row_idx == 0:
                ax.set_title(rf'{int(inf*100)}\% informed')

            # Row labels (left column only)
            if col_idx == 0:
                ax.set_ylabel(rf'$\rho={corr}$' + '\n' + r'Num patterns')

    # Set ticks
    for row in axes_query:
        for ax in row:
            ax.tick_params(axis='both', which='both', bottom=True, left=True, top=False, right=False)
            ax.set_xticks(x_tick_indices, all_net_sizes[x_tick_indices])
            ax.set_yticks(y_tick_indices, all_num_patterns[y_tick_indices])

    # Shared axis labels
    fig_query.text(0.5, 0.02, 'Network size', ha='center', fontsize=25)

    # Single colorbar
    cbar_ax = fig_query.add_axes([0.92, 0.15, 0.02, 0.7])
    cbar = fig_query.colorbar(im, cax=cbar_ax)
    cbar.set_label(r'Query success rate (\%)', fontsize=20)
    cbar.ax.tick_params(labelsize=16)

    fig_query.suptitle(r'Partial Cue Recovery (grey = not tested, below 90\% AR threshold)',
                       fontsize=22, y=0.98)
    plt.tight_layout(rect=[0, 0.03, 0.9, 0.96])

    if SAVE_PLOTS:
        output_path = OUTPUT_DIR / "partial_cue_recovery_5x4_heatmap.png"
        plt.savefig(output_path, dpi=DPI, bbox_inches='tight')
        print(f"Saved partial cue heatmap to: {output_path}")

    plt.show()

# %%
