#ifndef JSON_CONFIG_HPP
#define JSON_CONFIG_HPP

#include <string>
#include <vector>
#include <unordered_map>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <algorithm>
#include <cctype>

/**
 * Simple JSON config parser for simulation configs.
 * Handles the specific format generated by Python utils.py:
 *
 * {
 *   "type": "write",
 *   "patterns_file": "/path/to/patterns.data",
 *   "output_dir": "/path/to/output",
 *   "base_params": {"leak": 1.0, "drive_target": 6.0, ...},
 *   "varying_params": {"leak": [0.25, 0.5, 1.0], ...}
 * }
 */

class JsonConfig {
public:
    std::string type;
    std::string patterns_file;
    std::string metadata_file;  // Optional: path to pattern_metadata.json
    std::string input_dir;
    std::string output_dir;
    bool native_pattern_generation = false;  // If true, C++ generates patterns internally
    std::unordered_map<std::string, double> base_params;
    std::unordered_map<std::string, std::vector<double>> varying_params;

    static JsonConfig load(const std::string& filepath) {
        std::ifstream file(filepath);
        if (!file.is_open()) {
            throw std::runtime_error("Cannot open config file: " + filepath);
        }

        std::stringstream buffer;
        buffer << file.rdbuf();
        std::string content = buffer.str();

        JsonConfig config;
        config.parse(content);
        return config;
    }

    // Generate all parameter combinations (Cartesian product)
    std::vector<std::unordered_map<std::string, double>> generateCombinations() const {
        std::vector<std::unordered_map<std::string, double>> combinations;

        if (varying_params.empty()) {
            combinations.push_back(base_params);
            return combinations;
        }

        // Calculate total combinations
        size_t total = 1;
        std::vector<std::string> keys;
        std::vector<std::vector<double>> values;

        for (const auto& param : varying_params) {
            keys.push_back(param.first);
            values.push_back(param.second);
            total *= param.second.size();
        }

        // Generate all combinations
        for (size_t i = 0; i < total; ++i) {
            std::unordered_map<std::string, double> combo = base_params;
            size_t idx = i;

            for (size_t j = 0; j < keys.size(); ++j) {
                combo[keys[j]] = values[j][idx % values[j].size()];
                idx /= values[j].size();
            }

            combinations.push_back(combo);
        }

        return combinations;
    }

private:
    void parse(const std::string& content) {
        size_t pos = 0;
        skipWhitespace(content, pos);

        if (content[pos] != '{') {
            throw std::runtime_error("Expected '{' at start of JSON");
        }
        pos++;

        while (pos < content.size()) {
            skipWhitespace(content, pos);

            if (content[pos] == '}') break;
            if (content[pos] == ',') { pos++; continue; }

            std::string key = parseString(content, pos);
            skipWhitespace(content, pos);

            if (content[pos] != ':') {
                throw std::runtime_error("Expected ':' after key");
            }
            pos++;

            skipWhitespace(content, pos);

            if (key == "type") {
                type = parseString(content, pos);
            } else if (key == "patterns_file") {
                patterns_file = parseString(content, pos);
            } else if (key == "metadata_file") {
                metadata_file = parseString(content, pos);
            } else if (key == "input_dir") {
                input_dir = parseString(content, pos);
            } else if (key == "output_dir") {
                output_dir = parseString(content, pos);
            } else if (key == "native_pattern_generation") {
                native_pattern_generation = parseBool(content, pos);
            } else if (key == "base_params") {
                base_params = parseParamObject(content, pos);
            } else if (key == "varying_params") {
                varying_params = parseVaryingParams(content, pos);
            } else {
                skipValue(content, pos);
            }
        }
    }

    void skipWhitespace(const std::string& s, size_t& pos) {
        while (pos < s.size() && std::isspace(s[pos])) pos++;
    }

    std::string parseString(const std::string& s, size_t& pos) {
        skipWhitespace(s, pos);
        if (s[pos] != '"') {
            throw std::runtime_error("Expected '\"' at start of string");
        }
        pos++;

        std::string result;
        while (pos < s.size() && s[pos] != '"') {
            if (s[pos] == '\\' && pos + 1 < s.size()) {
                pos++;
            }
            result += s[pos++];
        }
        pos++; // skip closing quote
        return result;
    }

    double parseNumber(const std::string& s, size_t& pos) {
        skipWhitespace(s, pos);
        size_t start = pos;

        if (s[pos] == '-') pos++;
        while (pos < s.size() && (std::isdigit(s[pos]) || s[pos] == '.' || s[pos] == 'e' || s[pos] == 'E' || s[pos] == '+' || s[pos] == '-')) {
            if ((s[pos] == '+' || s[pos] == '-') && pos > start && s[pos-1] != 'e' && s[pos-1] != 'E') break;
            pos++;
        }

        return std::stod(s.substr(start, pos - start));
    }

    bool parseBool(const std::string& s, size_t& pos) {
        skipWhitespace(s, pos);
        if (pos + 4 <= s.size() && s.substr(pos, 4) == "true") {
            pos += 4;
            return true;
        }
        if (pos + 5 <= s.size() && s.substr(pos, 5) == "false") {
            pos += 5;
            return false;
        }
        throw std::runtime_error("Expected 'true' or 'false'");
    }

    std::vector<double> parseNumberArray(const std::string& s, size_t& pos) {
        std::vector<double> result;
        skipWhitespace(s, pos);

        if (s[pos] != '[') {
            throw std::runtime_error("Expected '[' at start of array");
        }
        pos++;

        while (pos < s.size()) {
            skipWhitespace(s, pos);
            if (s[pos] == ']') { pos++; break; }
            if (s[pos] == ',') { pos++; continue; }

            result.push_back(parseNumber(s, pos));
        }

        return result;
    }

    std::unordered_map<std::string, double> parseParamObject(const std::string& s, size_t& pos) {
        std::unordered_map<std::string, double> result;
        skipWhitespace(s, pos);

        if (s[pos] != '{') {
            throw std::runtime_error("Expected '{' at start of object");
        }
        pos++;

        while (pos < s.size()) {
            skipWhitespace(s, pos);
            if (s[pos] == '}') { pos++; break; }
            if (s[pos] == ',') { pos++; continue; }

            std::string key = parseString(s, pos);
            skipWhitespace(s, pos);

            if (s[pos] != ':') {
                throw std::runtime_error("Expected ':' after key");
            }
            pos++;

            result[key] = parseNumber(s, pos);
        }

        return result;
    }

    std::unordered_map<std::string, std::vector<double>> parseVaryingParams(const std::string& s, size_t& pos) {
        std::unordered_map<std::string, std::vector<double>> result;
        skipWhitespace(s, pos);

        if (s[pos] != '{') {
            throw std::runtime_error("Expected '{' at start of varying_params");
        }
        pos++;

        while (pos < s.size()) {
            skipWhitespace(s, pos);
            if (s[pos] == '}') { pos++; break; }
            if (s[pos] == ',') { pos++; continue; }

            std::string key = parseString(s, pos);
            skipWhitespace(s, pos);

            if (s[pos] != ':') {
                throw std::runtime_error("Expected ':' after key");
            }
            pos++;

            result[key] = parseNumberArray(s, pos);
        }

        return result;
    }

    void skipValue(const std::string& s, size_t& pos) {
        skipWhitespace(s, pos);

        if (s[pos] == '"') {
            parseString(s, pos);
        } else if (s[pos] == '{') {
            int depth = 1;
            pos++;
            while (pos < s.size() && depth > 0) {
                if (s[pos] == '{') depth++;
                else if (s[pos] == '}') depth--;
                pos++;
            }
        } else if (s[pos] == '[') {
            int depth = 1;
            pos++;
            while (pos < s.size() && depth > 0) {
                if (s[pos] == '[') depth++;
                else if (s[pos] == ']') depth--;
                pos++;
            }
        } else {
            while (pos < s.size() && s[pos] != ',' && s[pos] != '}' && s[pos] != ']') {
                pos++;
            }
        }
    }
};

#endif
