CC=g++ 
SRC := $(shell pwd)
INCLUDE_DIR := $(shell pwd)/include/
CFLAGS=-g -Wall -std=c++17

all : main

main: $(SRC)/correlated_patterns.cpp
	$(CC) $(CFLAGS) $(SRC)/correlated_patterns.cpp -o main -I$(INCLUDE_DIR)



